/**
 * Centralized Notification Types for LocalFix
 */
const NOTIFICATION_TYPES = {
  REQUEST_CREATED: 'REQUEST_CREATED',
  REQUEST_ASSIGNED: 'REQUEST_ASSIGNED',
  REQUEST_STATUS_CHANGED: 'REQUEST_STATUS_CHANGED',
  REQUEST_RESOLVED: 'REQUEST_RESOLVED',
  REQUEST_VERIFIED: 'REQUEST_VERIFIED',
  REQUEST_REOPENED: 'REQUEST_REOPENED',
  FEEDBACK_SUBMITTED: 'FEEDBACK_SUBMITTED',
  ADMIN_NEW_REQUEST: 'ADMIN_NEW_REQUEST',
  REQUEST_IN_PROGRESS: 'REQUEST_IN_PROGRESS'
};

module.exports = NOTIFICATION_TYPES;
